// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBIshgHOzs17d_m-7tq80zKidauefbnoc',
    appId: '1:448376984344:web:7ead463080d0cb5271446d',
    messagingSenderId: '448376984344',
    projectId: 'betpro-54221',
    authDomain: 'betpro-54221.firebaseapp.com',
    storageBucket: 'betpro-54221.appspot.com',
    measurementId: 'G-NYSE58V9NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj9kA-m8e9nNLyHYRN1e-jsPOBgfvibL8',
    appId: '1:448376984344:android:9850a74d1d87ae0871446d',
    messagingSenderId: '448376984344',
    projectId: 'betpro-54221',
    storageBucket: 'betpro-54221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb96_2afSNXqHLQ_-G09S7ggvqxFuGhBc',
    appId: '1:448376984344:ios:0b9cd133adfad31671446d',
    messagingSenderId: '448376984344',
    projectId: 'betpro-54221',
    storageBucket: 'betpro-54221.appspot.com',
    iosBundleId: 'com.example.betpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb96_2afSNXqHLQ_-G09S7ggvqxFuGhBc',
    appId: '1:448376984344:ios:bef8fc1f52e4792271446d',
    messagingSenderId: '448376984344',
    projectId: 'betpro-54221',
    storageBucket: 'betpro-54221.appspot.com',
    iosBundleId: 'com.example.betpro.RunnerTests',
  );
}
